site_name: Image-Charts
site_description: Image-Charts documentation
site_author: François-Guillaume Ribreau
site_url: https://documentation.image-charts.com

# Repository
repo_name: image-charts/documentation
repo_url: https://github.com/image-charts/documentation
edit_uri: ""

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TOKEN"]
  - auto

# Copyright
# copyright: 'Copyright &copy; Image-Charts'

nav:
  - Getting Started: getting_started.md
  - Pie Charts: pie_charts.md
  - Line Charts: line_charts.md
  - Bar Charts: bar_charts.md
  - Polar Charts: polar_charts.md
  - Graph Viz Charts: graph_viz_charts.md
  - Reference:
    - Chart Size: reference/Chart_Size.md
    - Chart Type: reference/Chart_Type.md
    - Data Format: reference/Data_Format.md
    - Color Format: reference/Color_Format.md
    - Chart Title: reference/Chart_Title.md
    - Grid Lines: reference/Grid_Lines.md
    - Legend Text and Style: reference/LegendTextAndStyle.md
    - Chart Label: reference/Chart_Label.md
    - Chart Margin: reference/Chart_Margin.md
    - Chart Axis: reference/Chart_Axis.md
    - Background Fill: reference/Background_Fill.md
    - Animation: reference/Animation.md
    - Output Format: reference/Output_Format.md
    - Post requests: reference/Post_requests.md
  - Enterprise: enterprise.md
  - Changelog: https://headwayapp.co/image-charts-changelog
  - Gallery: gallery.md

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: logo/rgb-rect-white@32.png
  logo: logo/rgb-rect-transparent@64.png

extra:
  social:
    - type: 'github'
      link: 'https://github.com/image-charts'
    - type: 'twitter'
      link: 'https://twitter.com/imagecharts'

# facelessuser.github.io/pymdown-extensions
# https://www.mkdocs.org/user-guide/configuration/#formatting-options
# https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L96
markdown_extensions:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.emoji
  # https://github.com/mkdocs/mkdocs/issues/777#issuecomment-308266201
  - markdown_include.include:
      base_path: docs
  # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#nested-fence-format
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
